### ISSUE TITLE
Could not launch framework java.lang.RuntimeException: Could not resolve mvn:org.eclipse.tycho/org.eclipse.osgi

### ISSUE THREAD

**Issue by marbon87** [openhab/openhab-docker#146]
Hi, 

i updated my docker setup on a rpi2 from openhab/openhab:2.1.0-armhf to openhab/openhab:2.2.0-armhf-alpine. I deleted the folders userdata/tmp and userdata/cache and added tty: true to my compose file, but it get the following error if i start the latest 2.2.0 image:

openhab.log
```
2017-12-27 13:31:34.409 [SEVERE] [org.apache.karaf.main.Main] - Could not launch framework
java.lang.RuntimeException: Could not resolve mvn:org.eclipse.tycho/org.eclipse.osgi/3.10.101.v20150820-1432
        at org.apache.karaf.main.util.SimpleMavenResolver.resolve(SimpleMavenResolver.java:59)
        at org.apache.karaf.main.Main.createClassLoader(Main.java:457)
        at org.apache.karaf.main.Main.launch(Main.java:254)
        at org.apache.karaf.main.Main.main(Main.java:179)
```

docker log:
```
...
+ chown -R openhab:openhab /openhab
+ exec su-exec openhab ./start.sh
Launching the openHAB runtime...
Could not resolve mvn:org.eclipse.tycho/org.eclipse.osgi/3.10.101.v20150820-1432
```

This is my docker-compose.yml-file:
```
 openhab2:
  container_name: openhab2
  environment:
   - OPENHAB_HTTPS_PORT=8443
  image: openhab/openhab:2.2.0-armhf-alpine
  restart: unless-stopped
  network_mode: "host"
  tty: true
  volumes:
   - "/etc/localtime:/etc/localtime:ro"
   - "/opt/openhab2/conf:/openhab/conf"
   - "/opt/openhab2/userdata:/openhab/userdata"
   - "/opt/openhab2/addons:/openhab/addons"
```

**Comment by cniweb** [comment]
Unfortunately, the update function in the current and old Docker images is not mature yet. I recommend to use a manual update here.

**Comment by marbon87** [comment]
Sorry, but what exactly do you mean by manual update? Is there any documentation for that? Thx

**Comment by marbon87** [comment]
I finally got 2.2.0 working on my pi, but not the alpine version, with the following steps:

1. stop and removed old openhab container
2. deleted userdata/tmp and userdata/cache
3. downloaded latest openhab2.2-image with `docker pull ...` (can also be done by docker-compose)
4. edited my docker-compose file to use the 2.2-docker-image but overrided the default command with `command: /bin/bash`, so i can execute the openhab update script manually out of the container
```
 openhab2:
  container_name: openhab2
  image: openhab/openhab:2.2.0-armhf-debian
  command: /bin/bash
  restart: unless-stopped
  network_mode: "host"
  tty: true
  volumes:
   - "/etc/localtime:/etc/localtime:ro"
   - "/usr/share/zoneinfo/Europe/Berlin:/etc/timezone:ro"
   - "/opt/openhab2/conf:/openhab/conf"
   - "/opt/openhab2/userdata:/openhab/userdata"
   - "/opt/openhab2/addons:/openhab/addons"
```
5. start the new setup from the compose file: `docker-compose up -d openhab2`
6. start a bash in the openhab-container with `docker exec -it openhab2 bash -li'
7. installed curl in the container with `apt-get update && apt-get install curl` (it is missing in the latest debian image)
8. start the update script at /openhab/runtime/bin/update
9. follow the instructions
10. stop the container
11. remove the command-argument `command: /bin/bash' from the docker-compose file
12. start the container again...
13. be happy :)
(13. on alpine: the start up failed (also with empty conf and userdata-folder) with the error `Error executing command: java.io.IOException: Unable to parse columns`
