### ISSUE TITLE
Segmentation fault while trying to list usb devices on pi3

### ISSUE THREAD

**Issue by ODINServ** [openhab/openhab-docker#162]
I'm trying to migrate my openhab 2.2 setup into a container on my pi-3 using the openhab/openhab:2.2.0-armhf-debian image.

The container wil run on the same pi as where my non docker setup is running without any issues.

However when i try to add a "RFXtrx433E USB 433.92MHz Transceiver"  from the rfxom binding the container crashes.
According to the java error log it try's to list USB devices (see hs_err log)

Since i cannot repoduce this with the amd64 image, and my current (non docker) setup of openhab 2.2.0 release is working fine i dont think there is an issue with the rfxcom binding.

Steps to reproduce on the pi 3

docker run \
        --name openhab-2.2.0-production \
        --net=host \
	-e USER_ID=1002 \
	-e OPENHAB_HTTP_PORT=8081 \
	-e OPENHAB_HTTPS_PORT=8444 \
	--tty \
	-v /etc/localtime:/etc/localtime:ro \
        -v /etc/timezone:/etc/timezone:ro \
        -d \
        openhab/openhab:2.2.0-armhf-debian

On the web interface:
* Standard setup
* Add RFXCom binding using the paper ui
* Add thing, RFXCom thing -> RFXtrx433E USB 433.92MHz Transceiver
<crash>

NOTE: It does not matter when pass i the --device=/dev/ttyUSB0 to the container.

Output of "docker logs" [docker_logs.txt](https://github.com/openhab/openhab-docker/files/1790678/docker_logs.txt)

Error file
[hs_err_pid160.log](https://github.com/openhab/openhab-docker/files/1790679/hs_err_pid160.log)

**Comment by wborn** [comment]
@martinvw did you ever use  successfully use RFXCom on a RPi3 with Docker?

The jd2xx.jar in the [lib directory](https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.rfxcom/lib) of the RFXCom Binding does seem to contain a architecture specific libjd2xx.so in /jni/linux/arm-hf/.

**Comment by martinvw** [comment]
I used it first on my pi 2 but I moved to a x64 inside Docker, so I never had that combination 🙂

**Comment by wildgers** [comment]
I encountered the same issue. 

Running the container with --privileged fixes this issue for now. Just adding --cap-add SYS_ADMIN wasn't enough.

**Comment by cniweb** [comment]
See Docker Docs:
https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
`--device=/dev/ttyUSB0`
I think is not enough.
Can you use:
`--device=/dev/ttyUSB0:rw`
Or this:
`--cap-add SYS_RAWIO`

**Comment by felixbrucker** [comment]
Same issue here, but i'm on regular amd64 arch.

`privileged: true`, `:rw`, `cap_add` and `chmod 777` all didn't help.

```
version: '2'
services:
  app:
    privileged: true
    cap_add:
      - ALL
    image: openhab/openhab:2.3.0-amd64-alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /media/ssd/docker/data/openhab/conf:/openhab/conf
      - /media/ssd/docker/data/openhab/userdata:/openhab/userdata
      - /media/ssd/docker/data/openhab/addons:/openhab/addons
    devices:
      - /dev/ttyACM0:/dev/ttyACM0:rw
    networks:
      internal:
        ipv4_address: 10.1.0.47
networks:
  internal:
    external:
      name: internal
```

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000000000037a6, pid=140, tid=0x00007f2113a2eae8
#
# JRE version: OpenJDK Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.8.0
# Distribution: Custom build (Wed Jun 13 18:28:11 UTC 2018)
# Problematic frame:
# C  0x00000000000037a6
#
# Core dump written. Default location: /openhab/userdata/core or core.140
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid140.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
#
Segmentation fault (core dumped)
```
