### ISSUE TITLE
can't figure out where permissions issue comes from

### ISSUE THREAD

**Issue by CodingSpiderFox** [openhab/openhab-docker#168]
Hello, 

I start docker as part of a docker-compose unit, but I get a permission denied error on the openhab.log when the container starts. 

```
  docker-openhab:
    image: "openhab/openhab:2.1.0-armhf"
    restart: always
    ports:
      - 8080:8080
      - 8443:8443
    tty: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/var/docker-data/openhab/addons:/openhab/addons:rw"
      - "/var/docker-data/openhab/conf:/openhab/conf:rw"
      - "/var/docker-data/openhab/userdata:/openhab/userdata:rw"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      USER_ID: "9001"
```
Also tried without USER_ID (I think 9001 was already default)

All files under /var/docker-data/openhab on the hosts belong to 9001:9001, permissions: rw r r

This is the error I get:

```
+ set -euo pipefail
+ IFS='
        '
+ NEW_USER_ID=9001
+ echo 'Starting with openhab user id: 9001'
Starting with openhab user id: 9001
+ id -u openhab
+ echo 'Create user openhab with id 9001'
Create user openhab with id 9001
+ adduser -u 9001 --disabled-password --gecos '' --home /openhab openhab
Warning: The home dir /openhab you specified already exists.
Adding user `openhab' ...
Adding new group `openhab' (9001) ...
Adding new user `openhab' (9001) with group `openhab' ...
The home directory `/openhab' already exists.  Not copying from `/etc/skel'.
adduser: Warning: The home directory `/openhab' does not belong to the user you are currently creating.
+ groupadd -g 14 uucp2
+ groupadd -g 16 dialout2
+ groupadd -g 18 dialout3
+ groupadd -g 32 uucp3
+ groupadd -g 997 gpio
+ adduser openhab dialout
Adding user `openhab' to group `dialout' ...
Adding user openhab to group dialout
Done.
+ adduser openhab uucp
Adding user `openhab' to group `uucp' ...
Adding user openhab to group uucp
Done.
+ adduser openhab uucp2
Adding user `openhab' to group `uucp2' ...
Adding user openhab to group uucp2
Done.
+ adduser openhab dialout2
Adding user `openhab' to group `dialout2' ...
Adding user openhab to group dialout2
Done.
+ adduser openhab dialout3
Adding user `openhab' to group `dialout3' ...
Adding user openhab to group dialout3
Done.
+ adduser openhab uucp3
Adding user `openhab' to group `uucp3' ...
Adding user openhab to group uucp3
Done.
+ adduser openhab gpio
Adding user `openhab' to group `gpio' ...
Adding user openhab to group gpio
Done.
+ case ${OPENHAB_VERSION} in
++ ls -A /openhab/userdata
+ '[' -z 'config
etc
jsondb
log
uuid' ']'
++ ls -A /openhab/conf
+ '[' -z 'items
rules
services
things' ']'
+ chown -R openhab:openhab /openhab
+ exec gosu openhab ./start.sh
Launching the openHAB runtime...
/openhab.log (Permission denied)
```

When I copy the files out of the container with docker cp, all the folders and files under /openhab in the container belong to root. What am I doing wrong?
