### ISSUE TITLE
Shutdown container gracefully

### ISSUE THREAD

**Issue by dimalo** [openhab/openhab-docker#211]
Hi everyone!
Thanks for this nice image, I switched to it two weeks ago.
Now it's running on an Odroid HC1 (armhf) with docker compose.
Unfortunately I couldn't get the alpine image to run so I chose the debian one.
At the moment I am running the 2.4.0.M6 version.

docker-compose.yml version 3
```YAML
  openhab:
    container_name: openhab
    #image: "openhab/openhab:2.4.0.M6-armhf-debian"
    build: /home/dima/openhab-docker/2.4.0.M6/armhf/debian #modified Dockerfile to download latest zulu-embedded and install procps for debugging
    restart: unless-stopped
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/opt/openhab/addons:/openhab/addons"
      - "/opt/openhab/conf:/openhab/conf"
      - "/opt/openhab/userdata:/openhab/userdata"
    environment:
      USER_ID: 9001
      GROUP_ID: 9001
      OPENHAB_HTTP_PORT: "xxxx"
      OPENHAB_HTTPS_PORT: "xxxx"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
```
I am also running a couple of other containers:
- frontail
- ~~influxdb~~
- ~~mosquitto~~ (Now with embedded broker)
- pihole
- unifi controller

I noticed that when stopping the container with 
`docker-compose stop openhab`
The issued SIGTERM signal runs into a timeout and after that the SIGKILL signal kills the container with Karaf still happily running. When I am logging stdout with `docker logs -f openhab` I get the system exit code of 137 -> killed.
There are no logs of Items being removed and things being disposed. I was using OH with systemd before, where the shutdown takes it's time and the log messages appear.

This caused a couple of flaws for me already:
- faulty .rrd files for RRD4J persistence
- file locks not deleted
- ~~random crashes and restarts because of JDK seg faults (actually I hope it's because of the kill corrupting any files which should be deleted otherwise)~~ Did figure out the Odroid tends to run unstable if it's max frequency is not capped

I tried a lot:
- update to latest zulu embedded
- `docker-compose stop -t 60 openhab`
- modify start.sh to detach the karaf process and have a trap running to be able to react on SIGTERM

I think the reason is the bash script with PID 1 which does not forward the TERM signal to it's child processes.
I can shutdown karaf with `docker exec openhab /openhab/runtime/bin/stop`. I just have not found a nice way to have the container intercept SIGTERM and execute the shutdown.
So far I researched [here](https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/) and [here](https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86).

Any help is appreciated 🤕
