### ISSUE TITLE
After updating the 2.4-alpine image all HTTP endpoints are broken

### ISSUE THREAD

**Issue by acidicX** [openhab/openhab-docker#229]
I successfully upgraded from 2.3 to 2.4 a while ago. While upgrading my system I pulled a newer 2.4 image yesterday and now all HTTP endpoints seem to be broken:

* `/start/index` alternates between a Jetty 404 page and a plain HTML site with template variables and no CSS
* all REST endpoints are 404
* basicui is 404

I am using `openhab/openhab:2.4.0-armhf-alpine` on a Raspberry Pi 3. Base system is arch linux. Docker: `Docker version 18.09.3-ce, build 774a1f4eee`

compose file:
```yml
version: '2.2'

services:
  openhab:
    image: "openhab/openhab:2.4.0-armhf-alpine"
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./volumes/openhab_addons:/openhab/addons"
      - "./volumes/openhab_conf:/openhab/conf"
      - "./volumes/openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      USER_ID: "1000"
      GROUP_ID: "1000"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin -Xmx512m"
      CRYPTO_POLICY: "unlimited"
```

OpenHab output (`docker-compose up`):

```
openhab_1  | ++ test -t 0
openhab_1  | ++ echo false
openhab_1  | + interactive=false
openhab_1  | + set -euo pipefail
openhab_1  | + IFS='
openhab_1  | 	'
openhab_1  | + '[' unlimited = unlimited ']'
openhab_1  | + '[' '!' -d /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/policy/unlimited ']'
openhab_1  | + echo 'Installing OpenJDK unlimited strength cryptography policy...'
openhab_1  | + mkdir /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/policy/unlimited
openhab_1  | Installing OpenJDK unlimited strength cryptography policy...
openhab_1  | + apk fix --no-cache openjdk8-jre-lib
openhab_1  | fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/armhf/APKINDEX.tar.gz
openhab_1  | fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/armhf/APKINDEX.tar.gz
openhab_1  | (1/1) Reinstalling openjdk8-jre-lib (8.201.08-r0)
openhab_1  | Executing java-common-0.1-r0.trigger
openhab_1  | OK: 123 MiB in 82 packages
openhab_1  | + rm -f /openhab/runtime/instances/instance.properties
openhab_1  | + rm -f /openhab/userdata/tmp/instances/instance.properties
openhab_1  | + NEW_USER_ID=1000
openhab_1  | + NEW_GROUP_ID=1000
openhab_1  | + echo 'Starting with openhab user id: 1000 and group id: 1000'
openhab_1  | + id -u openhab
openhab_1  | Starting with openhab user id: 1000 and group id: 1000
openhab_1  | ++ getent group 1000
openhab_1  | + '[' -z '' ']'
openhab_1  | Create group openhab with id 1000
openhab_1  | + echo 'Create group openhab with id 1000'
openhab_1  | + groupadd -g 1000 openhab
openhab_1  | Create user openhab with id 1000
openhab_1  | + echo 'Create user openhab with id 1000'
openhab_1  | + adduser -u 1000 -D -g '' -h /openhab -G openhab openhab
openhab_1  | + adduser openhab dialout
openhab_1  | + adduser openhab uucp
openhab_1  | + case ${OPENHAB_VERSION} in
openhab_1  | ++ ls -A /openhab/userdata
openhab_1  | + '[' -z 'Californium.properties
openhab_1  | backup
openhab_1  | cache
openhab_1  | config
openhab_1  | etc
openhab_1  | hs_err_pid16.log
openhab_1  | hs_err_pid24.log
openhab_1  | hs_err_pid25.log
openhab_1  | jsondb
openhab_1  | logs
openhab_1  | tmp' ']'
openhab_1  | ++ cmp /openhab/userdata/etc/version.properties /openhab/userdata.dist/etc/version.properties
openhab_1  | + '[' '!' -z ']'
openhab_1  | ++ ls -A /openhab/conf
openhab_1  | + '[' -z 'html
openhab_1  | icons
openhab_1  | items
openhab_1  | persistence
openhab_1  | rules
openhab_1  | scripts
openhab_1  | services
openhab_1  | sitemaps
openhab_1  | sounds
openhab_1  | things
openhab_1  | transform' ']'
openhab_1  | + '[' -d /etc/cont-init.d ']'
openhab_1  | + chown -R openhab:openhab /openhab
openhab_1  | + sync
openhab_1  | + '[' false == false ']'
openhab_1  | ++ IFS=' '
openhab_1  | ++ echo su-exec openhab tini -s ./start.sh
openhab_1  | + '[' 'su-exec openhab tini -s ./start.sh' == 'su-exec openhab tini -s ./start.sh' ']'
openhab_1  | + command=($@ server)
openhab_1  | + exec su-exec openhab tini -s ./start.sh server
openhab_1  | Launching the openHAB runtime...

```
