### ISSUE TITLE
Fatal Error when Launching a new instance

### ISSUE THREAD

**Issue by stratosmacker** [openhab/openhab-docker#27]
Launching the demo works, however running the docker image with volumes for userdata and conf seems to break something. I have built all three branches

On the console (docker run with debug):`
openhab_1  | [Fatal Error] :1:3: The markup in the document preceding the root element must be well-formed.`

On the web:

```
Problem accessing /start/index. Reason:

    Not Found

```

docker-compose:

```
openhab:
  build: .
  restart: always
  ports:
    - "8080:8080"
    - "8443:8443"
    - "5555:5555"
  net: "host"
  volumes:
    - ./openhab/userdata:/openhab/userdata
    - ./openhab/conf:/openhab/conf
  command: "debug"

```

Where is /start/index supposed to be? I'm not really a java guy but I am guessing the answer is obvious (and I am missing it).

That being said when this is resolved we ought to put this in the README so that it obvious is more obvious

**Comment by legacycode** [comment]
You are using relative path names in your volume configuration. Use following yaml:

```YAML
openhab:
  build: .
  restart: always
  net: host
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"
    - "/opt/openhab/userdata:/openhab/userdata"
    - "/opt/openhab/conf:/openhab/conf"
  command: debug
```
You don't need to expose the ports, because you are running in net:host mode and the ports are already available. Exposing ports in host mode have no effects.
