### ISSUE TITLE
KARAF_ETC is not valid: /openhab/userdata/etc

### ISSUE THREAD

**Issue by fex01** [openhab/openhab-docker#275]
Hi guys,

It seems like the container doesn't start successfully if you are either missing precreated folders (conf, userdata & addons) or if have already content in these folders.

I did also write a post in the openHAB forum: https://community.openhab.org/t/docker-restarting-karaf-etc-is-not-valid-openhab-userdata-etc

The short version:

My docker compose section for openHAB:
```
openhab:
    image: "openhab/openhab:2.5.0"
    container_name: openhab
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "${PWD}/openhab/addons:/openhab/addons"
      - "${PWD}/openhab/conf:/openhab/conf"
      - "${PWD}/openhab/userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      USER_ID: ${UID}
      GROUP_ID: ${GID}
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
    ports:
      - "8007:5007"
      - "8080:8080"
      - "8443:8443"
```

My tests:
1. ~/test1: no precreated folders, no chown / chmod, u/gid set to 1000 (main user) :x: 
2. ~/test2: no precreated folders, chown -R 1000:1000, u/gid set to 1000 :x:
3. ~/test3: no precreated folders, chown -R 9001:9001, u/gid set to 1000 (9001 being the default uid if no uid is set for the openHAB image) :x:
  b. stop - create userdata/etc/ - start again :x:
4. ~/test4: no precreated folders, chown -R 9001:9001, u/gid set to 9001 :x:
  b. stop - create userdata/etc/ - start again :x:
5. ~/test5: no precreated folders, chmod -R 777, u/gid set to 1000 :x:
  b. remove container - create userdata/etc/ - start again :x:
6. ~/test6: no precreated folders, chmod -R 777, chown -R 9001:9001, u/gid set to 9001 :x:
  b. remove container - create userdata/etc/ - start again :x:
7. /opt/openhab7: create user openhab7, precreated folders, chown -R openhab7:openhab7, u/gid set to openhab7's :white_check_mark:
8. ~/test8: precreated folders (./conf, ...), chown -R openhab7:openhab7, u/gid set to openhab7's :white_check_mark:
9. ~/test9: precreated folders in subfolder (./openhab/conf, ./openhab/addons, ...), chown -R openhab7:openhab7, u/gid set to openhab7's :white_check_mark:
10. ~/test10: precreated folders in subfolder, no chown / chmod, u/gid set to 1000 :white_check_mark:
