### ISSUE TITLE
WebUI not reachable

### ISSUE THREAD

**Issue by anionDev** [openhab/openhab-docker#325]
Hello,

Today I have spent several hours trying to get OpenHAB running using docker-compose. I have tried to run docker using the images `openhab:2.5.7`, `openhab:2.5.10`, `openhab:2.5.11` and `openhab:2.5.12-snapshot-alpine`.

I end up with this `docker-compose.yml`-file which should work as far as i know:

```
version: "3.9"

services:
  openhab:
    container_name: OpenHAB
    image: "openhab/openhab:2.5.11"
    restart: always
    network_mode: host
    volumes:
      - "D:\\<...>\\Volumes\\addons:/openhab/addons"
      - "D:\\<...>\\Volumes\\conf:/openhab/conf"
      - "D:\\<...>\\Volumes\\userdata:/openhab/userdata"
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - EXTRA_JAVA_OPTS=-Dfile.encoding=UTF8
      - USER_ID=9001
      - GROUP_ID=9001
```

The shared volumes on the host were always created and empty when starting the container.

With all versions i can reproduce the same behavior:

Docker says the container is running but I can not reach the WebUI, neither on `https://127.0.0.1:8443` nor on `http://localhost:8080`. (I have also tried something like `http://127.0.0.1:8443` and `https://127.0.0.1:8080`, specifing the ports in the docker-compose without using `network_mode: host`, etc., but this didn't changed anything.)
In the `conf`- and in the `userdata`-folder i can see some generated files but all 3 logfiles in `userdata\logs` remain empty.
I have read that it can last some minutes until OpenHAB is initalized and the WebUI is working. So I have waited (>10Minutes) but the WebUI is still not available.
When i look into the container the last output-lines are 
```
'/openhab/dist/userdata/./tmp/README' -> '/openhab/userdata/./tmp/README'
++ cmp /openhab/userdata/etc/version.properties /openhab/dist/userdata/etc/version.properties
+ '[' '!' -z ']'
+ chown -R openhab:openhab /openhab
+ sync
+ '[' -d /etc/cont-init.d ']'
+ sync
+ '[' false == false ']'
++ IFS=' '
++ echo gosu openhab tini -s ./start.sh
+ '[' 'gosu openhab tini -s ./start.sh' == 'gosu openhab tini -s ./start.sh' ']'
+ command=($@ server)
+ exec gosu openhab tini -s ./start.sh server
Launching the openHAB runtime...
```
The entire output does not contain any error-message.
(And also after `Launching the openHAB runtime...` I have waited several minutes.)

I still can not reach the WebUI.

What have I done wrong?
