### ISSUE TITLE
No UI to choose

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab-docker#39]
I just downloaded the latest docker image and started with some fresh config folders because my old OH2 docker image was getting old and some configuration was not correct.

However everything starts fine but I cannot choose any UI, did I do something wrong or is the latest snapshot a little of?

Docker compose file:
```
openhab:
  image: 'openhab/openhab:amd64-online'
  ports:
    - "8080:8080"
    - "8443:8443"
    - "5555:5555"
  net: "host"
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/etc/timezone:/etc/timezone:ro'
    - '/meru/docker-configs/openhab/userdata:/openhab/userdata'
    - '/meru/docker-configs/openhab/conf:/openhab/conf'
    - '/meru/docker-configs/openhab/addons:/openhab/addons'
  command: "server"
```
Screenshot:
![image](https://cloud.githubusercontent.com/assets/2625279/20964030/2ce9e2b0-bc70-11e6-92f7-b9bca2b027fc.png)

Log:
> 2016-12-07 11:23:44.227 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start
