### ISSUE TITLE
Can't access the web interface when running container in host mode

### ISSUE THREAD

**Issue by alexander-heimbuch** [openhab/openhab-docker#40]
Hey,

I'm struggling with accessing openhab's web interface when I'm running the container in host mode. It is reachable without the host mode but unfortunately I need the connection to the local avahi daemon (for usage with HomeKit service). In host mode I can discover the announced HomeKit service but I can't reach the web gui.

used image: `amd64-online [43ad6c9d8954]`
docker-compose:
```
openhab:
  image: 'openhab/openhab:amd64-online'
  restart: always
  container_name: openhab
  net: host
  ports:
    - 8080:8080
    - 8443:8443
    - 5555:5555
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ~/services/openhab/userdata:/openhab/userdata
    - ~/services/openhab/conf:/openhab/conf
```
