### ISSUE TITLE
Add openhab to dailout group

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-docker#71]
I've discovered after the recent changes that added an openhab user to the container and set it as the default that:

1. I can't override that behavior through the --user argument and therefore cannot use my own users. I'm not certain this is an issue with the Image yet but it is the only one that I run that will not take the --user argument. However, if I use -u root it does seem to take the root user.

2. I've set the openhab user on my host to 9001 to match the one in the container. However, that doesn't mean that group membership translates into the container. Consequently the openhab user inside the container is not a member of dialout and therefore cannot access /dev/ttyUSB0 where the zwave controller is.

I'm not actually certain how this access worked before the change to use openhab UID 9001. It seems like it still should of had some problems.

Anyway, right now the only way to access USB devices are to run with -u root or by temporarily changing the permissions on /dev/ttyUSB0 (since they change back on reboot) to allow all to read/write.

At a minimum this information should be added to the README. Ideally there should be a way that I can access USB devices without running as root.

**Comment by legacycode** [comment]
hi. could you please priovide me the full run command? I will try to reproduce the error. Have you also set the USER_ID env variable in your run command? You need to specify the --user and USER_ID to the same same id. With USER_ID you create a user with the right permission in the container and with --user you tell docker to use the user in the container. That would explain your problem.

**Comment by rkoshak** [comment]
I did not provide the environment variable, just the -u. It wasn't clear that both were required.

I'm using [Ansible to control this](https://docs.ansible.com/ansible/docker_container_module.html). The syntax is pretty close to docker-compose so it should be clear what I'm doing. If not I'll reverse engineer the command:

```
  - name: Update and restart openHAB
    docker_container:
      detach: True
      devices:
        - "/dev/ttyUSB0:/dev/ttyUSB0:rwm"
      env:
        USER_ID: 9001
      exposed_ports:
        - 8101
        - 8080
        - 8443
      hostname: chimera.koshak.net
      image: openhab/openhab:2.0.0-amd64
      log_driver: syslog
      name: openhab
      network_mode: host
      pull: True
      recreate: True
      restart: True
      restart_policy: always
      user: openhab:openhab
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - /mnt/config/openhab/conf:/openhab/conf
        - /mnt/config/openhab/userdata:/openhab/userdata
        - /mnt/config/openhab/addons:/openhab/addons
        - /mnt/config/openhab/.java:/openhab/.java
```

One thing to note, I've created an openhab:openhab on the host with UID:GID 9001:9001 as mentioned above.

With the command above, complete with the USER_ID environment variable passed in, I still am not successfully connecting to /dev/ttyUSB0.

Despite the groups appearing correct I'm still seeing the following in the zwave logs:

```
 2017-02-04 13:27:35.189 [ZWaveSerialHandler        ] - Connecting to serial port '/dev/ttyUSB0'
2017-02-04 13:27:47.167 [ZWaveThingHandler         ] - Controller handler not found. Cannot handle command without ZWave controller.
2017-02-04 13:27:47.204 [ZWaveThingHandler         ] - Controller handler not found. Cannot handle command without ZWave controller.
2017-02-04 13:27:47.214 [ZWaveThingHandler         ] - Controller handler not found. Cannot handle command without ZWave controller.
2017-02-04 13:27:47.225 [ZWaveThingHandler         ] - Controller handler not found. Cannot handle command without ZWave controller.
```

When I run as root (i.e. pass in `-u root:root` zwave is able to connect to the device just fine.

One final test, on the host if I try `tail -f /dev/ttyUSB0` as the openhab user it does it. When I try to do it within the container I get permission denied.


Of course, now that I've run a few tests I have no idea what the heck is going on now. I removed both the -u openhab:openhab as well as the env argument in an attempt to figure out why I was ending up as user root when I used `docker exec -it /bin/bash openhab` instead of user openhab like I used to be and now its working. Gah!

I guess for now I need to do some more experimentation to figure out what the "proper" way is before I update the Docker Install docs at docs.openhab.org. 

Feel free to close the issue. Somehow it is working for me now, I've no idea why.

One thing I would recommend though is if you must pass the USER_ID environment variable when using -u, that should be made more clear in the README.

Thanks!
